#!/bin/sh
# Set up rich core at bootup
### BEGIN INIT INFO
# Provides:          rich-core-pattern
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set the rich core pattern and create dir for dumps
# Description:       Catch core dumps as they occur and process them so that a
#        complete crash report can be sent to the crash report server.  This 
#        script initalizes the system for collecting the reports.
### END INIT INFO

# This file is part of sp-rich-core
#
# Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA

SW_VERSION_FILE=/etc/meego-release
COREDIR=/home/meego/core-dumps
CACHEDIR=/var/cache/rich-core-dumper

case "$1" in
  start|restart|force-reload)

	# Do not execute the script if we don't have the core dumper installed
	# (i.e. the package has been removed but not purged)
	test -x /usr/sbin/rich-core-dumper || exit 0

	# Create directory for core dumps and cached data if, and only if, they don't exist.
	test -x $COREDIR || mkdir -p $COREDIR
	test -x $CACHEDIR || mkdir -p $CACHEDIR

	# setup new core_pattern
	sysctl -q -w kernel.core_pattern='|/usr/sbin/rich-core-dumper --pid=%p --signal=%s --name=%e'
	;;

  stop)
  	# restore the backup-ed core_pattern only if it contains "rich-core-dumper" 
  	# keyword as it might have already been changed by someone else
	test -x $COREDIR || mkdir -p $COREDIR

	# Get MeeGo SW version.
	rel=$(grep "BUILD" $SW_VERSION_FILE)
	release="${rel##BUILD: }"
	echo "Enabling core dumps to $COREDIR/..."

	grep -q "rich-core-dumper" /proc/sys/kernel/core_pattern
  	if [ $? -eq 0 ]; then
		sysctl -q -w kernel.core_pattern=$COREDIR/%e-%s-%p-$release.core
	fi
  		
	;;
  
  *)
  	N=/etc/init.d/rich-core
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
