#!/bin/sh
# Returns crash ids matching given uuid from directory.

# This file is part of sp-rich-core
#
# Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
#
# Contact: meego-qa@lists.meego.com
# Authors: Sampo Saaristo <sampo.saaristo@sofica.fi>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
#
# Variables
#
COREPATH=""
UUIDPATTERN=""
UUID=""
#
# Helper functions
#
_parse_arguments()
{
  if [ $# -ne 2 ]; then
      echo "$0 Invalid arguments"
      exit 1
  else
      COREPATH=$1
      UUID=$2
      UUIDPATTERN=/home/meego/core-dumps/*$UUID*.rcore.lzo
  fi
}

_search_uuid()
{
    ls $UUIDPATTERN > /dev/null 2>&1
}

_print_crashids()
{
     for id in $UUIDPATTERN; do
	echo $id | sed  -e 's/\(.*\)-\(.*\).rcore.lzo/\2/'
     done
}

#
# Main program
#
_parse_arguments $*
_search_uuid
if [ $? -ne 0 ]; then
  exit 1
fi
_print_crashids
